DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  - BASH_SHELLCHECK
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - YAML_V8R

SHOW_ELAPSED_TIME: true
SARIF_REPORTER: true
GITHUB_STATUS_REPORTER: true

# Disable unnecessary stuff
FILEIO_REPORTER: false
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
