version: '2.1'

orbs:
  megalinter: relativesure/megalinter@2.0.0

workflows:
  run-megalinter:
    jobs:
      - megalinter/run:
          resource_class: kubearchitect/hetzner-ubuntu-kind
          context:
            - main-context
