name: Generate Index Pages

on:
  push:
    branches:
      - main

jobs:
  generate-indexes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run script to generate index pages
        run: node scripts/generate-indexes.mjs

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto-generate index pages"
          branch: main
          file_pattern: "**/*.mdx"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
